### ISSUE TITLE
Use a config for the router

### ISSUE THREAD

**Issue by 2O4** [dhost-project/dhost#138]
Use a config for the DOM router to allow the change of routes on all buttons and links in a central place.

**Comment by Djojo77** [comment]
```
const dapp_url = "/ipfs/{dapp_slug}/"
const dapp_slug = "test"
const URL = format(dapp_url, dapp_slug = dapp_slug)

return:
/ipfs/test/
```

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Template_literals
